"""numero1 = 5 
numero2 = 1 


try:
    print( numero1 + numero2)
    print("no se puecede ningun error")
except:
    print("se ha producido un error")
"""

a = 5
b = 2

 

try:
    print(a / b)
    print("no hay ningu error")
except TypeError as error3:
    print(error3)
    
    print("hay un error ")
